---
application:
  port: 8292

messaging:
  connection_address: kafka:9092
  # timeout waiting for initial version check on Kafka producer/consumer initialisation
  # 5000ms is usually sufficient, increase if problems with NoBrokersAvailable occur
  api_version_auto_timeout_ms: 5000

resource_driver:
  scripts_workspace: ./driver_files
  keep_files: False

adopt:
  skip_status_check: False
  adoptable_status_values: ['CREATE_COMPLETE','ADOPT_COMPLETE','RESUME_COMPLETE','CHECK_COMPLETE','UPDATE_COMPLETE']
   